name: Prepare
description: Prepares the repo for a typical CI job

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: 22.21.1
    - run: pnpm install --no-frozen-lockfile
      shell: bash